# -*- coding: utf-8 -*-
"""Query_vista_postgresToMongo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wi4IQGkyrucazMEOjJi0Kap__QPKnFNf
"""

import os
from dotenv import load_dotenv

# Load credentials from .env
load_dotenv()

!pip uninstall -y pymongo && pip install sqlalchemy psycopg2-binary pymongo openai

import psycopg2
import sys

def extract_schema_metadata(db_url, table_names=None):
    """
    Connects to the database using psycopg2 and returns a detailed text summary
    of the schema, including columns, types, defaults, and relationships.
    """

    # FIX: psycopg2 does not understand 'postgresql+psycopg2://'.
    # We must convert it to 'postgresql://'
    clean_url = db_url.replace("postgresql+psycopg2://", "postgresql://")

    try:
        conn = psycopg2.connect(clean_url)
        cur = conn.cursor()
    except Exception as e:
        return f"❌ CRITICAL ERROR: Could not connect to database.\nReason: {e}"

    # -------------------- GET TABLE LIST --------------------
    if table_names is None:
        try:
            cur.execute("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE';
            """)
            table_names = [t[0] for t in cur.fetchall()]
        except Exception as e:
            return f"Error fetching table list: {e}"

    if not table_names:
        return "⚠️ Connected to database, but found no tables in 'public' schema."

    final_output = []

    for table_name in table_names:
        output = []

        # -------------------- COLUMNS --------------------
        cur.execute("""
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
            ORDER BY ordinal_position;
        """, (table_name,))

        columns = cur.fetchall()
        if not columns:
            continue

        output.append(f"\n📋 Table: {table_name}")
        output.append("-" * 80)
        output.append(f"{'Column':<25} {'Type':<15} {'Nullable':<10} {'Default'}")
        output.append("-" * 80)

        for col in columns:
            col_name = col[0]
            col_type = col[1]
            is_null = col[2]
            default_val = str(col[3]) if col[3] else "None"
            # Truncate default value if it's too long (e.g., sequences)
            if len(default_val) > 30:
                default_val = default_val[:27] + "..."

            output.append(f"{col_name:<25} {col_type:<15} {is_null:<10} {default_val}")

        # -------------------- PRIMARY KEY --------------------
        cur.execute("""
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_schema = 'public'
              AND tc.table_name = %s
              AND tc.constraint_type = 'PRIMARY KEY';
        """, (table_name,))

        pk = [r[0] for r in cur.fetchall()]
        if pk:
            output.append("\n🔑 Primary Key:")
            output.append("   " + ", ".join(pk))

        # -------------------- FOREIGN KEYS (Outgoing) --------------------
        cur.execute("""
            SELECT
                kcu.column_name,
                ccu.table_name AS foreign_table,
                ccu.column_name AS foreign_column
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
            WHERE tc.table_schema = 'public'
              AND tc.table_name = %s
              AND tc.constraint_type = 'FOREIGN KEY';
        """, (table_name,))

        fk_rows = cur.fetchall()
        if fk_rows:
            output.append("\n🔗 Foreign Keys (Relations this table has):")
            for col, ft, fc in fk_rows:
                output.append(f"   [{col}] -> references -> {ft}.{fc}")

        # -------------------- REFERENCED BY (Incoming) --------------------
        # This helps the AI understand if this is a Parent table
        cur.execute("""
            SELECT
                tc.table_name AS child_table,
                kcu.column_name AS child_column
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = 'public'
              AND ccu.table_name = %s;
        """, (table_name,))

        refs = cur.fetchall()
        if refs:
            output.append("\n🔁 Referenced By (Tables linking to this one):")
            for t, c in refs:
                output.append(f"   {t}.{c} -> links to this table")

        final_output.append("\n".join(output))

    cur.close()
    conn.close()

    return "\n\n".join(final_output)


# --- Usage Example ---
if __name__ == "__main__":
    # Your provided URL (SQLAlchemy format)
    sql_url = os.environ.get("SQL_URL_ALT", "")

    print("Extracting Schema...")
    schema_text = extract_schema_metadata(sql_url)
    print(schema_text)

from openai import AzureOpenAI
import json
import os

# Azure OpenAI Configuration
client = AzureOpenAI(
    api_key=os.environ.get("AZURE_API_KEY", ""),
    api_version=os.environ.get("AZURE_API_VERSION", ""),
    azure_endpoint=os.environ.get("AZURE_ENDPOINT", "")
)

def generate_migration_plan(schema_text):
    """
    Sends schema to AI and gets a JSON execution plan.
    """

    system_prompt = """
    You are a Database Architect. I will give you a SQL schema.
    Map this to a MongoDB structure.

    Rules:
    1. Identify 'Root' tables (main entities like Users, Products).
    2. Identify 'Child' tables (details like Addresses, OrderItems).
    3. Decide to EMBED child tables if they are One-to-Few.
    4. Keep tables SEPARATE if they are One-to-Many (Infinite).

    Output ONLY valid JSON in this specific format:
    [
        {
            "sql_table": "users",
            "mongo_collection": "users",
            "embed": [
                {
                    "table": "user_addresses",
                    "foreign_key_column": "user_id",
                    "target_field": "addresses"
                }
            ]
        },
        {
            "sql_table": "orders",
            "mongo_collection": "orders",
            "embed": []
        }
    ]
    """

    response = client.chat.completions.create(
        model="gpt-4o",   # This is your Azure deployment name
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Here is the SQL Schema:\n{schema_text}"}
        ],
        temperature=0
    )

    content = response.choices[0].message.content

    # Remove markdown if AI returns it
    if "```json" in content:
        content = content.replace("```json", "").replace("```", "")

    return json.loads(content)


# Example usage
# schema = """
# CREATE TABLE users (
#     id INT PRIMARY KEY,
#     name TEXT
# );

# CREATE TABLE user_addresses (
#     id INT PRIMARY KEY,
#     user_id INT,
#     address TEXT
# );
# """

plan = generate_migration_plan(schema_text)
print(json.dumps(plan, indent=2))

import json
import datetime
import uuid
import decimal
from sqlalchemy import create_engine, text, inspect
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure, BulkWriteError

def safe_serialize(row):
    """
    Robust serializer for SQL rows.
    Handles UUID, Decimal, Date, Time, and Bytes.
    """
    # Convert SQLAlchemy Row to Dict
    if hasattr(row, '_mapping'):
        data = dict(row._mapping)
    else:
        data = dict(row)

    clean_data = {}

    for key, value in data.items():
        # 1. Handle Decimals (Money/Numeric)
        if isinstance(value, decimal.Decimal):
            clean_data[key] = float(value)

        # 2. Handle UUIDs (common in Postgres)
        elif isinstance(value, uuid.UUID):
            clean_data[key] = str(value)

        # 3. Handle Dates & Datetimes
        elif isinstance(value, (datetime.date, datetime.datetime)):
            clean_data[key] = value.isoformat()

        # 4. Handle Time (without date)
        elif isinstance(value, datetime.time):
            clean_data[key] = value.strftime("%H:%M:%S")

        # 5. Handle Bytes (rare, but causes crashes)
        elif isinstance(value, bytes):
            try:
                clean_data[key] = value.decode('utf-8')
            except:
                clean_data[key] = "<binary_data_skipped>"

        # 6. Standard types
        else:
            clean_data[key] = value

    return clean_data

def execute_migration(sql_url, mongo_url, migration_plan):
    print("\n🚀 Starting Robust Migration...")

    # 1. Connect to SQL
    # Fix URL prefix if needed
    if sql_url.startswith("postgres://"):
        sql_url = sql_url.replace("postgres://", "postgresql+psycopg2://")
    elif "postgresql+psycopg2" not in sql_url:
        sql_url = sql_url.replace("postgresql://", "postgresql+psycopg2://")

    try:
        sql_engine = create_engine(sql_url)
        # Test connection
        with sql_engine.connect() as test_conn:
            pass
        inspector = inspect(sql_engine)
        existing_tables = set(inspector.get_table_names())
        print("✅ Connected to SQL Database.")
    except Exception as e:
        print(f"❌ CRITICAL: SQL Connection Failed. {e}")
        return

    # 2. Connect to MongoDB
    try:
        mongo_client = MongoClient(mongo_url, serverSelectionTimeoutMS=5000)
        mongo_client.server_info() # Trigger connection check
        mongo_db = mongo_client["migrated_db"]
        print("✅ Connected to MongoDB.")
    except ConnectionFailure as e:
        print(f"❌ CRITICAL: MongoDB Connection Failed. {e}")
        return

    # 3. Execute Plan
    with sql_engine.connect() as conn:

        for job in migration_plan:
            root_table = job.get('sql_table')
            target_collection = job.get('mongo_collection')

            # --- SAFETY CHECK 1: Does table exist? ---
            # We try to match the table name loosely to handle case sensitivity
            actual_table_name = None
            if root_table in existing_tables:
                actual_table_name = root_table
            else:
                # Case-insensitive lookup
                for t in existing_tables:
                    if t.lower() == root_table.lower():
                        actual_table_name = t
                        break

            if not actual_table_name:
                print(f"⚠️ SKIPPING: Table '{root_table}' not found in SQL database.")
                continue

            print(f"🔄 Processing: {actual_table_name} -> {target_collection}...")

            try:
                # --- QUERY EXECUTION ---
                # We use quotes "{}" to ensure special characters/casing don't break queries
                query = text(f'SELECT * FROM "{actual_table_name}"')
                result = conn.execute(query)

                documents_batch = []
                count = 0

                for row in result:
                    doc = safe_serialize(row)
                    row_id = doc.get('id') or doc.get('ID') or doc.get('uuid')

                    # --- EMBEDDING LOGIC ---
                    if 'embed' in job and job['embed'] and row_id:
                        for embed_rule in job['embed']:
                            child_table = embed_rule.get('table')
                            fk_col = embed_rule.get('foreign_key_column')
                            target_field = embed_rule.get('target_field')

                            # Verify child table exists
                            if child_table not in existing_tables:
                                # Try lowercase match
                                match = next((t for t in existing_tables if t.lower() == child_table.lower()), None)
                                if match: child_table = match
                                else: continue # Skip if child doesn't exist

                            try:
                                # Fetch children
                                child_query = text(f'SELECT * FROM "{child_table}" WHERE "{fk_col}" = :rid')
                                child_rows = conn.execute(child_query, {"rid": row_id})
                                doc[target_field] = [safe_serialize(c) for c in child_rows]
                            except Exception as embed_err:
                                print(f"    ⚠️ Warning: Could not embed {child_table} for ID {row_id}: {embed_err}")
                                doc[target_field] = []

                    documents_batch.append(doc)

                    # --- BATCH INSERT (Batch Size 1000) ---
                    if len(documents_batch) >= 1000:
                        try:
                            mongo_db[target_collection].insert_many(documents_batch)
                            count += len(documents_batch)
                            documents_batch = []
                        except BulkWriteError as bwe:
                            print(f"    ⚠️ MongoDB Write Error: {bwe.details}")

                # Insert remaining
                if documents_batch:
                    mongo_db[target_collection].insert_many(documents_batch)
                    count += len(documents_batch)

                print(f"    ✅ Migrated {count} documents.")

            except Exception as table_err:
                print(f"❌ ERROR migrating table {actual_table_name}: {table_err}")

    print("\n🏁 Migration Task Completed.")

# --- MOCK USAGE ---
# if __name__ == "__main__":
#     # NOTE: Replace these with your real URLs
#     SQL_URL = "postgresql+psycopg2://neondb_owner:YOUR_PASSWORD@your-host.neon.tech/neondb"
#     MONGO_URL = "mongodb+srv://user:pass@cluster.mongodb.net/"

#     # Example Plan (Ensure casing matches your actual DB if possible, but script will try to auto-fix)
#     plan = [
#         {
#             "sql_table": "Employee",  # Script will look for "Employee" or "employee"
#             "mongo_collection": "employees",
#             "embed": []
#         }
#     ]

    # execute_migration(SQL_URL, MONGO_URL, plan)

pip install "pymongo[srv]"

# main.py

# ... paste the 3 functions above here ...

def main():
    # 1. Configuration
    SQL_URL = os.environ.get("SQL_URL_ALT", "")
    MONGO_URL = os.environ.get("MONGO_URL", "")
    USE_AI = True # Set to True if you have an API Key

    # 2. Phase 1: Inspector
    print("--- Phase 1: Extracting Schema ---")
    try:
        schema_text = extract_schema_metadata(SQL_URL)
        print("Schema extracted successfully.")
    except Exception as e:
        print(f"Error connecting to SQL: {e}")
        return

    # 3. Phase 2: Architect
    print("--- Phase 2: Generating Migration Plan ---")
    migration_plan = []

    if USE_AI:
        migration_plan = generate_migration_plan(schema_text)
    else:
        # HARDCODED EXAMPLE (Use this to test without paying for AI)
        # Assuming you have a table 'users' and 'addresses' in Postgres
        print("Using Mock Plan (AI Disabled)")
        migration_plan = [
            {
                "sql_table": "users",
                "mongo_collection": "users",
                "embed": [
                    {
                        "table": "addresses",
                        "foreign_key_column": "user_id",
                        "target_field": "address_list"
                    }
                ]
            }
        ]

    print(f"Plan: {json.dumps(migration_plan, indent=2)}")

    # 4. Phase 3: Executor
    print("--- Phase 3: Executing Migration ---")
    try:
        execute_migration(SQL_URL, MONGO_URL, migration_plan)
        print("Migration Complete!")
    except Exception as e:
        print(f"Error during migration: {e}")

if __name__ == "__main__":
    main()



import json
import logging
import os
import sys
import decimal
import uuid
import datetime
from typing import Dict, List

# 1. Install these: pip install sqlalchemy psycopg2-binary pymongo openai tqdm
from sqlalchemy import create_engine, text, inspect
from pymongo import MongoClient
from tqdm import tqdm

# 2. Azure OpenAI Import
from openai import AzureOpenAI

# --- CONFIGURATION: LOGGING ---
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

# ==========================================
# PHASE 1: HUMAN INTERFACE (The Reviewer)
# ==========================================
class HumanReviewer:
    """
    Manages the 'Human-in-the-Loop' workflow.
    Saves the AI plan to disk and pauses for your edits.
    """
    def __init__(self, filename="migration_blueprint.json"):
        self.filename = filename

    def save_draft(self, plan: List[Dict]):
        try:
            with open(self.filename, 'w') as f:
                json.dump(plan, f, indent=4)
            print(f"\n[HITL] 📝 DRAFT PLAN SAVED TO: {os.path.abspath(self.filename)}")
        except Exception as e:
            logging.error(f"Could not save draft: {e}")

    def wait_for_human_approval(self) -> List[Dict]:
        print("\n" + "="*60)
        print("✋ SYSTEM PAUSED FOR HUMAN REVIEW")
        print("="*60)
        print(f"1. Open '{self.filename}' in your text editor.")
        print("2. Review the schema mapping.")
        print("   - Rename fields in 'column_mapping' (e.g., 'user_name': 'userName')")
        print("   - Set columns to null to DROP them.")
        print("   - Verify 'embed' logic.")
        print("3. Save the file.")
        print("4. Press [ENTER] here to continue, or type 'exit' to cancel.")
        print("="*60)

        while True:
            user_input = input("Ready to execute? > ").strip().lower()
            if user_input == 'exit':
                print("Migration cancelled by user.")
                sys.exit(0)

            try:
                with open(self.filename, 'r') as f:
                    modified_plan = json.load(f)
                print(f"✅ Plan loaded! Contains instructions for {len(modified_plan)} tables.")
                return modified_plan
            except json.JSONDecodeError as e:
                print(f"❌ ERROR: Invalid JSON syntax. Please fix the file.\nDetails: {e}")
            except Exception as e:
                print(f"❌ ERROR: Could not read file: {e}")

# ==========================================
# PHASE 2: DISCOVERY (Metadata Extraction)
# ==========================================
class DataProfiler:
    def __init__(self, sql_url):
        # Auto-fix connection string for SQLAlchemy
        if sql_url.startswith("postgres://"):
            sql_url = sql_url.replace("postgres://", "postgresql+psycopg2://")
        elif "postgresql+psycopg2" not in sql_url:
            sql_url = sql_url.replace("postgresql://", "postgresql+psycopg2://")

        self.engine = create_engine(sql_url)
        self.inspector = inspect(self.engine)

    def get_metadata(self):
        try:
            tables = self.inspector.get_table_names()
        except Exception as e:
            print(f"❌ Connection Error: {e}")
            return []

        schema_summary = []
        for t in tables:
            cols = self.inspector.get_columns(t)
            col_list = [f"{c['name']} ({c['type']})" for c in cols]

            fks = self.inspector.get_foreign_keys(t)
            fk_list = []
            for fk in fks:
                constrained = fk.get('constrained_columns', ['unknown'])
                ref_table = fk.get('referred_table', 'unknown')
                fk_list.append(f"{constrained}->{ref_table}")

            schema_summary.append({
                "table": t,
                "columns": col_list,
                "fks": fk_list
            })
        return schema_summary

# ==========================================
# PHASE 3: AZURE AI ARCHITECT
# ==========================================
class SchemaArchitect:
    def __init__(self, endpoint, api_key, api_version, deployment_name):
        """
        Initializes the Azure OpenAI Client
        """
        self.client = AzureOpenAI(
            api_key=api_key,
            api_version=api_version,
            azure_endpoint=endpoint
        )
        self.deployment_name = deployment_name

    def draft_initial_plan(self, metadata) -> List[Dict]:
        print("🤖 Azure AI (GPT-4o) is analyzing schema...")

        system_prompt = """
        You are a Database Migration Architect.
        Input: SQL Schema Metadata.
        Output: A strict JSON Migration Plan.

        For each table, generate this object:
        {
            "sql_table": "source_table_name",
            "mongo_collection": "target_collection_name (camelCase)",
            "column_mapping": {
                "sql_col_name": "new_json_field_name",
                "hidden_col": null
            },
            "embed": [
                {
                    "child_table": "child_table_name",
                    "fk_col": "foreign_key_in_child",
                    "target_field": "list_name_in_mongo"
                }
            ]
        }

        Rules:
        1. Rename snake_case SQL columns to camelCase JSON fields.
        2. Identify 1-to-many relations that should be embedded.
        3. Return ONLY valid JSON. No Markdown.
        """

        try:
            # Send schema to Azure GPT-4o
            # Limiting to 10 tables to ensure we fit in context window if DB is huge
            metadata_snippet = json.dumps(metadata[:10], indent=2)

            response = self.client.chat.completions.create(
                model=self.deployment_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Schema Metadata:\n{metadata_snippet}"}
                ],
                temperature=0
            )

            content = response.choices[0].message.content

            # Cleaning potential markdown formatting
            if "```" in content:
                content = content.replace("```json", "").replace("```", "")

            return json.loads(content)

        except Exception as e:
            print(f"❌ Azure AI Request Failed: {e}")
            return []

# ==========================================
# PHASE 4: EXECUTION ENGINE
# ==========================================
class ETLEngine:
    def __init__(self, sql_url, mongo_url):
        if "postgresql+psycopg2" not in sql_url:
            sql_url = sql_url.replace("postgresql://", "postgresql+psycopg2://")

        self.sql_engine = create_engine(sql_url)
        self.mongo_client = MongoClient(mongo_url)
        self.mongo_db = self.mongo_client["migrated_db"]

    def _transform_row(self, row, mapping: Dict):
        # Convert row to dict
        if hasattr(row, '_mapping'): source_data = dict(row._mapping)
        else: source_data = dict(row)

        final_doc = {}

        for sql_col, val in source_data.items():
            # Check Mapping Logic
            target_key = sql_col

            if mapping:
                if sql_col in mapping:
                    if mapping[sql_col] is None: continue # Drop column
                    target_key = mapping[sql_col] # Rename column

            # Type Serialization (Fixes JSON crashes)
            if isinstance(val, decimal.Decimal): val = float(val)
            elif isinstance(val, uuid.UUID): val = str(val)
            elif isinstance(val, (datetime.date, datetime.datetime)): val = val.isoformat()
            elif isinstance(val, bytes): continue

            final_doc[target_key] = val

        return final_doc

    def execute(self, plan):
        print("\n🚀 Starting Execution Phase...")

        with self.sql_engine.connect() as conn:
            for job in plan:
                src_table = job['sql_table']
                tgt_coll = job['mongo_collection']
                col_map = job.get('column_mapping', {})

                print(f"Processing: {src_table} -> {tgt_coll}")

                # Check table existence
                if not self.sql_engine.dialect.has_table(conn, src_table):
                    print(f"⚠️ SKIPPING {src_table}: Not found in DB.")
                    continue

                # Fetch Rows (Streaming)
                try:
                    query = text(f'SELECT * FROM "{src_table}"')
                    result = conn.execution_options(yield_per=1000).execute(query)

                    batch = []
                    count = 0

                    for row in tqdm(result, desc="Migrating Rows", unit="rows"):

                        # 1. Transform Root Document
                        doc = self._transform_row(row, col_map)

                        # 2. Handle Embeddings (if defined in plan)
                        if 'embed' in job and job['embed']:
                            root_id = row._mapping.get('id') or row._mapping.get('ID')
                            if root_id:
                                for embed_rule in job['embed']:
                                    child_tbl = embed_rule['child_table']
                                    fk = embed_rule['fk_col']
                                    target_field = embed_rule['target_field']

                                    c_query = text(f'SELECT * FROM "{child_tbl}" WHERE "{fk}" = :rid')
                                    children = conn.execute(c_query, {"rid": root_id})

                                    doc[target_field] = [
                                        self._transform_row(c, {}) for c in children
                                    ]

                        batch.append(doc)

                        if len(batch) >= 1000:
                            self.mongo_db[tgt_coll].insert_many(batch)
                            count += len(batch)
                            batch = []

                    if batch:
                        self.mongo_db[tgt_coll].insert_many(batch)
                        count += len(batch)

                    print(f"✅ Migrated {count} documents to {tgt_coll}")

                except Exception as e:
                    print(f"❌ Error migrating {src_table}: {e}")

# ==========================================
# MAIN CONFIGURATION
# ==========================================
def main():
    print("🏢 AZURE-POWERED MIGRATION SYSTEM 🏢")

    # --- 1. CREDENTIALS ---
    # SQL Source
    SQL_URL = os.environ.get("SQL_URL", "")
    MONGO_URL = os.environ.get("MONGO_URL", "")

    # Azure OpenAI Configuration
    AZURE_ENDPOINT = os.environ.get("AZURE_ENDPOINT", "")
    AZURE_API_KEY = os.environ.get("AZURE_API_KEY", "")
    AZURE_API_VERSION = os.environ.get("AZURE_API_VERSION", "")
    DEPLOYMENT_NAME = "gpt-4o"  # Ensure this matches your Azure Deployment Name

    # --- 2. DISCOVERY ---
    print("\n--- Phase 1: Profiling Data ---")
    profiler = DataProfiler(SQL_URL)
    metadata = profiler.get_metadata()
    if not metadata:
        print("❌ System Exit: Could not read source database.")
        return

    # --- 3. AI DRAFTING (Azure) ---
    print("\n--- Phase 2: Azure AI Drafting ---")
    architect = SchemaArchitect(AZURE_ENDPOINT, AZURE_API_KEY, AZURE_API_VERSION, DEPLOYMENT_NAME)
    draft_plan = architect.draft_initial_plan(metadata)

    # --- 4. HUMAN REVIEW ---
    print("\n--- Phase 3: Human Review ---")
    reviewer = HumanReviewer("migration_blueprint.json")
    reviewer.save_draft(draft_plan)

    # !!! SYSTEM WAITS HERE FOR YOU TO EDIT THE JSON FILE !!!
    final_plan = reviewer.wait_for_human_approval()

    # --- 5. EXECUTION ---
    print("\n--- Phase 4: Execution ---")
    engine = ETLEngine(SQL_URL, MONGO_URL)
    engine.execute(final_plan)

    print("\n✅ Migration Complete.")

if __name__ == "__main__":
    main()

import sqlite3
import pandas as pd
from sqlalchemy import create_engine

# Path to SQLite DB
sqlite_path = "/content/olist.sqlite"

# Neon PostgreSQL connection URL
postgres_url = os.environ.get("SQL_URL", "")

# Connect to SQLite
sqlite_conn = sqlite3.connect(sqlite_path)

# Create Neon connection
engine = create_engine(postgres_url)

# Get all tables from SQLite
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    sqlite_conn
)

tables = tables['name'].tolist()

print("Tables found:", tables)

# Migrate each table
for table in tables:

    print(f"Migrating table: {table}")

    df = pd.read_sql_query(f"SELECT * FROM {table}", sqlite_conn)

    df.to_sql(
        table,
        engine,
        if_exists="replace",
        index=False,
        chunksize=1000
    )

    print(f"Finished: {table}")

print("Migration Completed 🚀")

pip install sqlalchemy psycopg2-binary pymongo openai python-dotenv

from pymongo import MongoClient

"""# queries validation"""

import json
import decimal
import datetime
import uuid
from bson.objectid import ObjectId # Changed import
from sqlalchemy import create_engine, text, inspect
from pymongo import MongoClient
from openai import AzureOpenAI

# ==========================================
# 1. CONFIGURATION & CREDENTIALS
# ==========================================
# NOTE: In production, store these in .env files!
SQL_URL = os.environ.get("SQL_URL", "")
MONGO_URL = os.environ.get("MONGO_URL", "")
MONGO_DB_NAME = "migrated_db" # <-- Replace with your target DB name

# Azure OpenAI Credentials
AZURE_ENDPOINT = os.environ.get("AZURE_ENDPOINT", "")
AZURE_API_KEY = os.environ.get("AZURE_API_KEY", "")
AZURE_API_VERSION = os.environ.get("AZURE_API_VERSION", "")
DEPLOYMENT_NAME = "gpt-4o"

# client = AzureOpenAI(
#     api_key=os.environ.get("AZURE_API_KEY", ""),
#     api_version=os.environ.get("AZURE_API_VERSION", ""),
#     azure_endpoint=os.environ.get("AZURE_ENDPOINT", "")
# )
# ==========================================
# 2. SERIALIZATION HELPERS
# ==========================================
def serialize_sql(row):
    """Converts SQL data types to standard Python dicts."""
    data = dict(row._mapping) if hasattr(row, '_mapping') else dict(row)
    for k, v in data.items():
        if isinstance(v, decimal.Decimal): data[k] = float(v)
        elif isinstance(v, uuid.UUID): data[k] = str(v)
        elif isinstance(v, (datetime.date, datetime.datetime)): data[k] = v.isoformat()
    return data

def serialize_mongo(doc):
    """Converts MongoDB specifics (like ObjectId/Datetime) to string."""
    for k, v in doc.items():
        if isinstance(v, ObjectId): doc[k] = str(v)
        elif isinstance(v, (datetime.date, datetime.datetime)): doc[k] = v.isoformat()
        elif isinstance(v, list):
            doc[k] =[serialize_mongo(item) if isinstance(item, dict) else item for item in v]
        elif isinstance(v, dict):
            doc[k] = serialize_mongo(v)
    return doc

# ==========================================
# 3. CORE VALIDATOR CLASS
# ==========================================
class SchemaAwareValidator:
    def __init__(self):
        # 1. Init AI
        self.ai_client = AzureOpenAI(
            api_key=AZURE_API_KEY,
            api_version=AZURE_API_VERSION,
            azure_endpoint=AZURE_ENDPOINT
        )

        # 2. Init DBs
        print("🔌 Connecting to SQL (Neon)...")
        self.sql_engine = create_engine(SQL_URL)

        print("🔌 Connecting to NoSQL (MongoDB Atlas)...")
        self.mongo_client = MongoClient(MONGO_URL)
        self.mongo_db = self.mongo_client[MONGO_DB_NAME]
        print("✅ Databases Connected.\n")

        # 3. Extract Schemas on Startup
        self.sql_schema = self._extract_sql_schema()
        self.mongo_schema = self._extract_mongo_schema()

    def _extract_sql_schema(self) -> str:
        """Reads SQL Tables and Columns to build AI context."""
        print("📊 Extracting SQL Schema...")
        inspector = inspect(self.sql_engine)
        schema_dict = {}

        try:
            for table in inspector.get_table_names():
                columns = [f"{c['name']} ({c['type']})" for c in inspector.get_columns(table)]
                schema_dict[table] = columns
            return json.dumps(schema_dict, indent=2)
        except Exception as e:
            print(f"⚠️ SQL Schema extraction failed: {e}")
            return "{}"

    def _extract_mongo_schema(self) -> str:
        """Reads a sample document from each Mongo collection to build AI context."""
        print("📊 Extracting MongoDB Schema (Sample Documents)...")
        schema_dict = {}

        try:
            collections = self.mongo_db.list_collection_names()
            for coll in collections:
                # Fetch 1 document to infer schema structure and embeddings
                sample_doc = self.mongo_db[coll].find_one()
                if sample_doc:
                    schema_dict[coll] = serialize_mongo(sample_doc)
                else:
                    schema_dict[coll] = "Empty Collection"
            return json.dumps(schema_dict, indent=2)
        except Exception as e:
            print(f"⚠️ Mongo Schema extraction failed: {e}")
            return "{}"

    def translate_nl_to_queries(self, natural_language_query: str) -> dict:
        """Feeds both schemas to Azure GPT-4o to generate accurate queries."""
        print(f"\n🧠 Asking AI to translate: '{natural_language_query}'...")

        system_prompt = f"""
        You are an Enterprise Database Architect validating a data migration from PostgreSQL to MongoDB.
        I will provide you with a Natural Language question.
        You must write a PostgreSQL Query AND a MongoDB Aggregation Pipeline that answer the question.

        CRITICAL INSTRUCTIONS:
        1. Use the [SQL SCHEMA] provided to formulate the correct SQL query (note exact column names).
        2. Use the [MONGO SCHEMA] provided to formulate the correct Mongo pipeline (note exact field names, camelCasing, and embedded arrays).

        [SQL SCHEMA]
        {self.sql_schema}

        [MONGO SCHEMA (Sample Documents showing structure)]
        {self.mongo_schema}

        OUTPUT FORMAT:
        Output ONLY a strict JSON object with this exact structure:
        {{
            "sql_query": "SELECT ...",
            "mongo_collection": "collection_name",
            "mongo_pipeline": [{{"$match": ...}}, {{"project": ...}}]
        }}
        """

        response = self.ai_client.chat.completions.create(
            model=DEPLOYMENT_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": natural_language_query}
            ],
            response_format={ "type": "json_object" },
            temperature=0  # 0 ensures deterministic, accurate code generation
        )

        content = response.choices[0].message.content
        return json.loads(content)

    def execute_and_compare(self, nl_query: str):
        """Executes the AI-generated queries and prints the side-by-side comparison."""
        try:
            # 1. Translate Query
            queries = self.translate_nl_to_queries(nl_query)

            sql_query = queries.get("sql_query")
            mongo_coll = queries.get("mongo_collection")
            mongo_pipeline = queries.get("mongo_pipeline")

            print("-" * 70)
            print(f"🐘 SQL Query      : {sql_query}")
            print(f"🍃 Mongo Pipeline : db.{mongo_coll}.aggregate({json.dumps(mongo_pipeline)})")
            print("-" * 70)

            # 2. Execute SQL
            sql_results =[]
            with self.sql_engine.connect() as conn:
                result = conn.execute(text(sql_query))
                sql_results =[serialize_sql(row) for row in result]

            # 3. Execute MongoDB
            mongo_results =[]
            if mongo_coll in self.mongo_db.list_collection_names():
                cursor = self.mongo_db[mongo_coll].aggregate(mongo_pipeline)
                mongo_results =[serialize_mongo(doc) for doc in cursor]
            else:
                print(f"⚠️ Warning: MongoDB collection '{mongo_coll}' does not exist.")

            # 4. Print Comparison Results
            print("\n📊 --- VALIDATION RESULTS ---")
            print(f"🐘 PostgreSQL Returned: {len(sql_results)} records.")
            print(f"🍃 MongoDB Returned   : {len(mongo_results)} records.\n")

            if len(sql_results) > 0 or len(mongo_results) > 0:
                print("🐘 PostgreSQL Sample Data:")
                print(json.dumps(sql_results[:2], indent=2))

                print("\n🍃 MongoDB Sample Data:")
                print(json.dumps(mongo_results[:5], indent=2))

            # Simple Integrity Check
            if len(sql_results) == len(mongo_results):
                print("\n✅ VALIDATION PASSED: Record counts match!")
            else:
                print("\n⚠️ VALIDATION FAILED: Record counts differ. Your data might not be migrated properly, or the query mappings are complex.")

        except Exception as e:
            print(f"\n❌ ERROR during execution: {e}")


# ==========================================
# 4. INTERACTIVE TERMINAL APP
# ==========================================
if __name__ == "__main__":
    print("======================================================")
    print(" 🕵️ SCHEMA-AWARE AI MIGRATION VALIDATOR")
    print("======================================================\n")

    validator = SchemaAwareValidator()

    print("\n💡 TIP: Try asking questions that involve JOINs in SQL to see how Mongo handles embedded data.")

    while True:
        print("\n" + "="*54)
        user_input = input("Ask your database a question (or type 'exit'):\n> ")

        if user_input.lower() in ['exit', 'quit', 'q']:
            print("Goodbye!")
            break

        validator.execute_and_compare(user_input)

