services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass123
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-ui
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8081:80"

  couchdb:
    image: couchdb:3
    container_name: couchdb-db
    restart: always
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin123
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  mysql_data:
  couchdb_data: